// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgiUfMm5_o6Oz6NYqmmYw32QiFEZT3J1g',
    appId: '1:388543729869:web:f6e4e508ace51ad0d11984',
    messagingSenderId: '388543729869',
    projectId: 'trackmate-5d2ab',
    authDomain: 'trackmate-5d2ab.firebaseapp.com',
    storageBucket: 'trackmate-5d2ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVsmBm4CERZMrnyTTn_loSDnlz0LHw0yI',
    appId: '1:388543729869:android:208a37ee465b1440d11984',
    messagingSenderId: '388543729869',
    projectId: 'trackmate-5d2ab',
    storageBucket: 'trackmate-5d2ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvK30ygx-QQT0OVVy7jeo_SumXzvtUPbQ',
    appId: '1:388543729869:ios:85e580f242a0d325d11984',
    messagingSenderId: '388543729869',
    projectId: 'trackmate-5d2ab',
    storageBucket: 'trackmate-5d2ab.appspot.com',
    iosBundleId: 'com.example.trackmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvK30ygx-QQT0OVVy7jeo_SumXzvtUPbQ',
    appId: '1:388543729869:ios:85e580f242a0d325d11984',
    messagingSenderId: '388543729869',
    projectId: 'trackmate-5d2ab',
    storageBucket: 'trackmate-5d2ab.appspot.com',
    iosBundleId: 'com.example.trackmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgiUfMm5_o6Oz6NYqmmYw32QiFEZT3J1g',
    appId: '1:388543729869:web:63995e79aa7748bad11984',
    messagingSenderId: '388543729869',
    projectId: 'trackmate-5d2ab',
    authDomain: 'trackmate-5d2ab.firebaseapp.com',
    storageBucket: 'trackmate-5d2ab.appspot.com',
  );
}
